Repository project-GAZA/GazaFront, pull requests merged in 2023-12, with the labels that each got.

#8 ✨ feat: 응원 메세지 스크롤 바 디자인 시안 적용
  src/app/_components/MessageComponent.tsx
  src/app/_components/Sections/ShowComment.tsx
  src/app/_components/Sections/section.style.ts
  src/app/_components/component.style.ts
Labels: UI

#13 [fix]검색창 수정
  .env.production
  src/app/_components/common/Main.tsx
  src/app/_components/common/common.style.ts
  src/app/api/message/route.ts
  src/app/page.tsx
  src/utils/api.ts
Labels: 🐛BUG, ☎️API

#17 [recfactor] toast커스텀 훅
  src/app/_components/Sections/InputSection.tsx
  src/app/_components/Sections/ShowGazaMap.tsx
  src/app/_components/common/Main.tsx
  src/app/_components/modal/Comment.tsx
  src/app/_components/modal/ShareModal.tsx
  src/hooks/useCustomToast.tsx
  tsconfig.json
Labels: ⚒️REFACTOR

#19 [refector] 모달창 디자인 작업 + 컨텐츠 내용 변수화 + PG연동전UI
  src/app/_components/Sections/InputSection.tsx
  src/app/_components/modal/Comment.tsx
  src/app/_components/modal/Donate.tsx
  src/app/_components/modal/ShareModal.tsx
  src/app/_components/modal/modal.style.ts
  src/assets/svg/ExplainSendMoney/ExplainSendMoney1.svg
  src/assets/svg/ExplainSendMoney/ExplainSendMoney2.svg
  src/assets/svg/ExplainSendMoney/ExplainSendMoney3.svg
  src/constants/index.ts
  src/constants/korean.ts
  src/types/data.ts
  src/types/props.ts
Labels: UI, 🐛BUG, ⚒️REFACTOR, 🖥️FEATURE

#21 [feat,refactor]사용자 정보 입력창 생성 , 스타일 객체로 정리
  package.json
  src/app/_components/ExplainComponent.tsx
  src/app/_components/MessageComponent.tsx
  src/app/_components/Sections/ExplainSectoin.tsx
  src/app/_components/Sections/InputSection.tsx
  src/app/_components/Sections/ShowComment.tsx
  src/app/_components/Sections/ShowGazaMap.tsx
  src/app/_components/Sections/ShowInfo1.tsx
  src/app/_components/Sections/section.style.ts
  src/app/_components/common/Header.tsx
  src/app/_components/common/MobileNav.tsx
  src/app/_components/common/common.style.ts
  src/app/_components/component.style.ts
  src/app/_components/modal/Comment.tsx
  src/app/_components/modal/Donate.tsx
  src/app/_components/modal/RegistModal.tsx
  src/app/_components/modal/modal.style.ts
  src/app/api/donate/route.ts
  src/constants/korean.ts
  src/lib/gtag.ts
  src/style/SectionStyle.css
  src/style/globals.css
  src/types/data.ts
  src/types/props.ts
  src/utils/api.ts
  yarn.lock
Labels: UI, ⚒️REFACTOR, ☎️API

#24 [fix] lint error => 배포안되는 에러 수정
  src/types/data.ts
  src/utils/usefull.ts
Labels: 🔨HOTFIX

#25 [feat] 기부금 팝업으로 생성한 댓글은 표시! => 빠른 체킹을 위해 스스로 머지햇습니다.
  src/app/_components/MessageComponent.tsx
  src/app/_components/Sections/InputSection.tsx
  src/app/_components/component.style.ts
  src/app/_components/modal/Donate.tsx
  src/app/_components/modal/RegistModal.tsx
  src/app/api/message/route.ts
  src/assets/svg/gifticon.svg
  src/types/data.ts
  src/types/props.ts
Labels: UI, ☎️API

#28 [refactor] fetch코드 리팩토링, 설명부분 변수로 초기화(한글,영어대비)
  .eslintrc.json
  src/app/_components/Sections/ExplainSectoin.tsx
  src/app/_components/Sections/InputSection.tsx
  src/app/_components/Sections/ShowComment.tsx
  src/app/_components/Sections/section.style.ts
  src/app/_components/common/Main.tsx
  src/app/_components/modal/Comment.tsx
  src/app/_components/modal/Donate.tsx
  src/app/_components/modal/RegistModal.tsx
  src/app/page.tsx
  src/constants/index.ts
  src/constants/korean.ts
  src/types/data.ts
  src/types/props.ts
  src/utils/api.ts
  src/utils/usefull.ts
Labels: ⚒️REFACTOR, ☎️API

#29 !HOTFIX : 무한 스크롤 버그 검토 요청
  src/app/_components/Sections/ShowComment.tsx
  src/app/_components/Sections/section.style.ts
  src/app/_components/common/Header.tsx
Labels: 🔨HOTFIX
