Repository project-GAZA/GazaFront, pull requests merged in 2024-01, with the labels that each got.

#36 [UI] Header font 수정
  src/app/_components/common/Header.tsx
Labels: UI

#38 [feat] UI오류 수정
  src/app/_components/Sections/InputSection.tsx
  src/app/_components/Sections/ShowComment.tsx
  src/app/_components/Sections/section.style.ts
Labels: UI

#50 [main] DEV사항 업데이트
  src/app/_components/MessageComponent.tsx
  src/app/_components/Sections/InputSection.tsx
  src/app/_components/Sections/ShowComment.tsx
  src/app/_components/Sections/section.style.ts
  src/app/_components/common/MobileNav.tsx
  src/app/_components/common/common.style.ts
Labels: 🎛️Infra

#64 🐛 fix: 이슈 #49 댓글 Sort 오류 수정 / 무한스크롤 best 버그 수정
  src/app/_components/Sections/ShowComment.tsx
Labels: 🐛BUG

#62 dev->main 배포
  .env.development
  .env.production
  .github/workflows/main.yml
  .gitignore
  next.config.js
  package.json
  src/app/_components/Sections/ShowComment.tsx
  src/app/_components/Sections/ShowGazaMap.tsx
  src/app/api/donate/[id]/route.ts
  src/app/api/donate/all/route.ts
  src/app/api/login/route.ts
  src/app/api/message/[id]/route.ts
  src/app/api/message/count/route.ts
  src/app/api/message/route.ts
  src/app/api/message/type/[id]/route.ts
  src/app/gazaadmin/donate/_components/DonateModifyModal.tsx
  src/app/gazaadmin/donate/_components/DonateTable.tsx
  src/app/gazaadmin/donate/page.tsx
  src/app/gazaadmin/page.tsx
  src/app/page.tsx
  src/hooks/useCustomToast.tsx
  src/types/data.ts
  src/utils/api.ts
  tsconfig.json
  yarn.lock
Labels: 배포

#67 ✨ feat: seo 적용 코드 리팩토링 1차 구현
  package-lock.json
  package.json
  src/app/_components/ExplainComponent.module.scss
  src/app/_components/ExplainComponent.tsx
  src/app/_components/MessageComponent.module.scss
  src/app/_components/MessageComponent.tsx
  src/app/_components/Sections/ShowInfo.tsx
  src/app/_components/common/Header.module.scss
  src/app/_components/common/Header.tsx
  src/app/_components/common/Main.module.scss
  src/app/_components/common/Main.tsx
  src/app/_components/common/MobileNav.module.scss
  src/app/_components/common/MobileNav.tsx
  yarn.lock
Labels: ⚒️REFACTOR

#70 Joo hello section - 스토리북 추가했습니다.
  .eslintrc.json
  .gitignore
  package.json
  src/component/HelloSection/Button.module.scss
  src/component/HelloSection/Button.tsx
  src/stories/Button.stories.tsx
  tsconfig.json
  yarn.lock
Labels: 🖥️FEATURE
